In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score

Считайте датасет из файла train.csv (данные о выживаемости на Титанике).

In [14]:
data = pd.read_csv('train.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Выберите и обоснуйте метрику качества - 2 балла

F1-score учитывает пропущенных выживших и ошибочные предсказания выживания. Дополнительно accuracy, чтобы видеть долю верных ответов

Разбиение датасета на тренировочную/тестовую выборки - 1 балл

In [15]:
X = pd.concat(
    [data[['Pclass', 'SibSp', 'Parch', 'Fare']],
     pd.get_dummies(data['Sex'], prefix='sex', drop_first=True)],
    axis=1
)
y = data['Survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=2023, test_size=0.25, stratify=y
)
X_train.head()

     Pclass  SibSp  Parch      Fare  sex_male
805       3      0      0    7.7750      True
55        1      0      0   35.5000      True
325       1      0      0  135.6333     False
543       2      1      0   26.0000      True
556       1      1      0   39.6000     False

Произведено измерение качества константного предсказания (например, наиболее частотный класс/случайное предсказание) - 1 балл

In [16]:
dummy_clf = DummyClassifier(strategy='most_frequent')
dummy_clf.fit(X_train, y_train)
y_pred_dummy = dummy_clf.predict(X_test)

print(f'Accuracy {accuracy_score(y_test, y_pred_dummy)}')
print(f'F1 {f1_score(y_test, y_pred_dummy, zero_division=0)}')

Accuracy 0.6143497757847534
F1 0.0

ML-модель обучена на тренировочной выборке - 3 балла

In [17]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)
y_pred_log_reg = log_reg.predict(X_test_scaled)

Измерение качества на отложенной выборке с использованием ранее выбранной метрики - 1 балл

In [18]:
print(f'Accuracy {accuracy_score(y_test, y_pred_log_reg)}')
print(f'F1 {f1_score(y_test, y_pred_log_reg, zero_division=0)}')

Accuracy 0.7668161434977578
F1 0.6941176470588235