In [4]:
import requests
import pandas as pd
import psycopg2

Получить информацию обо всех книгах и сохранить в pd.DataFrame - 1 балл

In [5]:
url = 'https://www.anapioficeandfire.com/api'
books = []
page = 1
while True:
    items = requests.get(
        f'{url}/books?page={page}&pageSize=50'
    ).json()
    if not items:
        break
    books += items
    page += 1

df_books = pd.DataFrame(books)
print('Книг:', len(df_books))
df_books.head()

Книг: 12

,url,name,isbn,authors,numberOfPages,publisher,country,mediaType,released,characters,povCharacters
0,https://www.anapioficeandfire.com/api/books/1,A Game of Thrones,978-0553103540,[George R. R. Martin],694,Bantam Books,United States,Hardcover,1996-08-01T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/books/2,A Clash of Kings,978-0553108033,[George R. R. Martin],768,Bantam Books,United States,Hardback,1999-02-02T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/books/3,A Storm of Swords,978-0553106633,[George R. R. Martin],992,Bantam Books,United States,Hardcover,2000-10-31T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/books/4,The Hedge Knight,978-0976401100,[George R. R. Martin],164,Dabel Brothers Publishing,United States,GraphicNovel,2005-03-09T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/books/5,A Feast for Crows,978-0553801507,[George R. R. Martin],784,Bantam Books,United Status,Hardcover,2005-11-08T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...

Получить информацию обо всех домах Вестероса (Houses) и сохранить в pd.DataFrame - 1 балл

In [7]:
houses = []
page = 1
while True:
    items = requests.get(
        f'{url}/houses?page={page}&pageSize=50'
    ).json()
    if not items:
        break
    houses += items
    page += 1

df_houses = pd.DataFrame(houses)
print('Домов:', len(df_houses))
df_houses.head()

Домов: 444

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/1,House Algood,The Westerlands,"A golden wreath, on a blue field with a gold b...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[]
1,https://www.anapioficeandfire.com/api/houses/2,House Allyrion of Godsgrace,Dorne,"Gyronny Gules and Sable, a hand couped Or",No Foe May Pass,[],[Godsgrace],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/285,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/3,House Amber,The North,,,[],[],,,,,,,[],[],[]
3,https://www.anapioficeandfire.com/api/houses/4,House Ambrose,The Reach,"Or, semy of ants gules",Never Resting,[],[],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/5,House Appleton of Appleton,The Reach,"Or, an apple tree eradicated proper fructed gu...",,[],[Appleton],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[]

Получить информацию обо всех домах Вестероса, у которых есть девиз, и сохранить в pd.DataFrame - 2 балла

In [12]:
houses_words = []
page = 1
while True:
    items = requests.get(
        f'{url}/houses?hasWords=true&page={page}&pageSize=50'
    ).json()
    if not items:
        break
    houses_words += items
    page += 1

df_house_words = pd.DataFrame(houses_words)
print('Домов с девизом:', len(df_house_words))
df_house_words[['name', 'words']].head()

Домов с девизом: 68

                             name                  words
0     House Allyrion of Godsgrace        No Foe May Pass
1                   House Ambrose          Never Resting
2        House Arryn of the Eyrie       As High as Honor
3        House Ashford of Ashford  Our Sun Shines Bright
4  House Baratheon of Storm's End       Ours is the Fury

Установить библиотеку psycopg2 (pip install psycopg2-binary)
Подключиться к БД - 1 балл

In [13]:
pip install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\d_v_o\appdata\roaming\python\python39\site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe -m pip install --upgrade pip' command.

In [14]:
host = 'hh-pgsql-public.ebi.ac.uk'
port = 5432
database = 'pfmegrnargs'
user = 'reader'
password = 'NWDMCE5xdipIjRrp'

conn = psycopg2.connect(
    dbname=database, user=user, password=password, host=host, port=port
)

Получите 10 строк таблицы rnc_database - 2 балла

In [26]:
conn.rollback()

In [27]:
with conn.cursor() as cursor:
    cursor.execute('SELECT * FROM rnacen.rnc_database LIMIT 10')
    rnc_rows = cursor.fetchall()

rnc_rows

InsufficientPrivilege: permission denied for schema rnacen
LINE 1: SELECT * FROM rnacen.rnc_database LIMIT 10
                      ^

Авторы ограничили права на доступ к базе, выполнить последние две задачи нельзя

Сохраните полученные данные в pd.DataFrame - 1 балл
Получите display_name, num_sequences, num_organisms и url для 10 строк - 2 балла